### ISSUE TITLE
KeywordOutsideEngine Issue

### ISSUE THREAD

**Issue by TomG1993** [Azure/PSDocs.Azure#24] opened 2021-01-07 10:41 UTC
Hello,

Not sure this is the right place for this but I am using PSDocs along inside a powershell script to create a wiki page for azure devops. 

It had been working fine but now out of nowhere it breaks when I run: 

#region Create WIKI MarkDown Content
Write-Output "Creating mark down table for wiki"
Document 'Create-MarkdownTable' {
$date = Get-Date -UFormat "%d/%m/%Y %R"
Section Summary {
"This is the work item list for the build created:  $date"
}
Section 'Work items'{
if ($InputObject.Count -lt 1)
{
"No work items are associated"
}
foreach($item in $InputObject)
{
"#$item"
}
}
}

Specifically:

Document 'Create-MarkdownTable' {

Has anything changed to PSDocs that may have caused this.

It throws an error of:

The property 'KeywordOutsideEngine' cannot be found on this object. Verify that the property exists.
At C:\Users\tom.gorton\Documents\WindowsPowerShell\Modules\PSDocs\0.7.0\PSDocs.psm1:389 char:10
+          Write-Error -Message $LocalizedHelp.KeywordOutsideEngine -Ca ...
+          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], PropertyNotFoundException
    + FullyQualifiedErrorId : PropertyNotFoundStrict

**Comment by BernieWhite** [comment] 2021-01-08 06:21
@TomG1993 Thanks for the question and reporting. This repository is for PSDocs for Azure.

You can log this over in the main PSDocs repository which I can see you have already done (Duplicate of BernieWhite/PSDocs#118).

I'll close this issue because your code is using the PSDocs engine instead.

**Closed by BernieWhite** 2021-01-08 06:21 UTC
Labels: question
